// Builds the site from src/.
//
//   src/template.html  markup + CSS, split at <!--/head--> into head and body
//   src/main.js        the whole Three.js scene and page behaviour
//
// Outputs:
//   index.html     complete standalone document, what gets hosted
//   artifact.html  body-only variant for pasting into a preview host
//
// Run: npm run build

import { execSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';

const SITE = {
  url: 'https://anshumanvyas.dev',
  title: 'Anshuman Vyas | Aerospace Engineer',
  description:
    'Aerospace engineer in Ottawa working on orbital mechanics, space robotics and ' +
    'the hardware around them. Satellite trajectory models, a 6-DOF capture manipulator, ' +
    'LiDAR reconstruction.',
  image: 'og.png',
  locale: 'en_CA'
};

execSync(
  'npx esbuild src/main.js --bundle --minify --format=iife --target=es2019 --outfile=bundle.js',
  { stdio: 'inherit' }
);

const tpl = readFileSync('src/template.html', 'utf8');
const js = readFileSync('bundle.js', 'utf8');

const MARK = '<!--/head-->';
if (!tpl.includes(MARK)) {
  throw new Error(`src/template.html is missing the ${MARK} marker that splits head from body`);
}
const [rawHead, body] = tpl.split(MARK);

// The template's own <title> is the short form. The hosted page wants the longer,
// searchable one, so swap it here rather than keeping two copies of the markup.
const head = rawHead.replace(/<title>[\s\S]*?<\/title>/, `<title>${SITE.title}</title>`);

const meta = `<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="color-scheme" content="dark">
<meta name="theme-color" content="#04060D">
<meta name="description" content="${SITE.description}">
<meta name="author" content="Anshuman Vyas">
<link rel="canonical" href="${SITE.url}/">

<meta property="og:type" content="website">
<meta property="og:site_name" content="Anshuman Vyas">
<meta property="og:locale" content="${SITE.locale}">
<meta property="og:title" content="${SITE.title}">
<meta property="og:description" content="${SITE.description}">
<meta property="og:url" content="${SITE.url}/">
<meta property="og:image" content="${SITE.url}/${SITE.image}">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta property="og:image:alt" content="Anshuman Vyas, aerospace engineer">

<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="${SITE.title}">
<meta name="twitter:description" content="${SITE.description}">
<meta name="twitter:image" content="${SITE.url}/${SITE.image}">

<link rel="icon" href="favicon.svg" type="image/svg+xml">
<link rel="apple-touch-icon" href="apple-touch-icon.png">
`;

// Function replacer on purpose: the minified Three.js bundle contains a variable
// named `$`, and a plain string replacement would let JavaScript expand $& / $` / $'
// inside it and silently corrupt the code. That produced a blank page once already.
const inject = (s) => s.replace('/*__BUNDLE__*/', () => js);

const BANNER = `<!--
  GENERATED FILE. Do not edit this file directly.
  Edit src/template.html or src/main.js, then run: npm run build
-->`;

writeFileSync(
  'index.html',
  `<!doctype html>
${BANNER}
<html lang="en">
<head>
${meta}${head.trim()}
</head>
<body>
${inject(body).trim()}
</body>
</html>
`
);

writeFileSync('artifact.html', inject(tpl.replace(MARK, '')));

console.log('wrote index.html and artifact.html');
