// Builds every page from src/.
//
//   src/<page>.html   markup + CSS, split at <!--/head--> into head and body
//   src/<entry>.js    the JavaScript that page needs
//
// Each page in PAGES is bundled and written to its own output path. index.html
// is the landing page; work pages get their own directory so the URL is clean.
//
// Run: npm run build

import { execSync } from 'node:child_process';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';

const SITE = {
  url: 'https://anshumanvyas.dev',
  locale: 'en_CA'
};

const PAGES = [
  {
    src: 'src/template.html',
    entry: 'src/main.js',
    out: 'index.html',
    alsoBodyOnly: 'artifact.html',
    base: '',
    title: 'Anshuman Vyas | Aerospace Engineer',
    description:
      'Aerospace engineer in Ottawa working on orbital mechanics, space robotics and ' +
      'the hardware around them. Satellite trajectory models, a 6-DOF capture manipulator, ' +
      'LiDAR reconstruction.',
    image: 'og.png',
    canonical: '/'
  },
  {
    src: 'src/work-l1.html',
    entry: 'src/page.js',
    out: 'work/l1-transfer/index.html',
    base: '../../',
    title: 'Slingshot to L1 | Anshuman Vyas',
    description:
      'Modelling the transfer from a 235 x 19,500 km Earth parking orbit to a halo orbit ' +
      'about the Sun-Earth L1 point: four perigee raises, escape to the sphere of influence, ' +
      'a Lambert arc, and a halo found in the circular restricted three-body problem.',
    image: 'og.png',
    canonical: '/work/l1-transfer/'
  }
];

const BANNER = `<!--
  GENERATED FILE. Do not edit this file directly.
  Edit the matching file in src/, then run: npm run build
-->`;

const MARK = '<!--/head-->';

// Function replacer on purpose: the minified Three.js bundle contains a variable
// named `$`, and a plain string replacement would let JavaScript expand $& / $` / $'
// inside it and silently corrupt the code. That produced a blank page once already.
const inject = (s, js) => s.replace('/*__BUNDLE__*/', () => js);

for (const page of PAGES) {
  const bundleFile = `bundle.${page.out.replace(/[\/.]/g, '_')}.js`;
  execSync(
    `npx esbuild ${page.entry} --bundle --minify --format=iife --target=es2019 --outfile=${bundleFile}`,
    { stdio: 'inherit' }
  );

  const tpl = readFileSync(page.src, 'utf8');
  const js = readFileSync(bundleFile, 'utf8');

  if (!tpl.includes(MARK)) throw new Error(`${page.src} is missing the ${MARK} marker`);
  const [rawHead, body] = tpl.split(MARK);
  const head = rawHead.replace(/<title>[\s\S]*?<\/title>/, `<title>${page.title}</title>`);

  const b = page.base;
  const meta = `<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="color-scheme" content="dark">
<meta name="theme-color" content="#04060D">
<meta name="description" content="${page.description}">
<meta name="author" content="Anshuman Vyas">
<link rel="canonical" href="${SITE.url}${page.canonical}">

<meta property="og:type" content="website">
<meta property="og:site_name" content="Anshuman Vyas">
<meta property="og:locale" content="${SITE.locale}">
<meta property="og:title" content="${page.title}">
<meta property="og:description" content="${page.description}">
<meta property="og:url" content="${SITE.url}${page.canonical}">
<meta property="og:image" content="${SITE.url}/${page.image}">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="630">
<meta property="og:image:alt" content="Anshuman Vyas, aerospace engineer">

<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:title" content="${page.title}">
<meta name="twitter:description" content="${page.description}">
<meta name="twitter:image" content="${SITE.url}/${page.image}">

<link rel="icon" href="${b}favicon.svg" type="image/svg+xml">
<link rel="apple-touch-icon" href="${b}apple-touch-icon.png">
`;

  const doc = `<!doctype html>
${BANNER}
<html lang="en">
<head>
${meta}${head.trim()}
</head>
<body>
${inject(body, js).trim()}
</body>
</html>
`;

  mkdirSync(dirname(page.out) === '.' ? '.' : dirname(page.out), { recursive: true });
  writeFileSync(page.out, doc);
  if (page.alsoBodyOnly) writeFileSync(page.alsoBodyOnly, inject(tpl.replace(MARK, ''), js));
  console.log('wrote', page.out);
}
