/* Mission viewer for the L1 project page.
 *
 * Three acts, each rendered in its own unit system because the scales involved
 * span five orders of magnitude (a 6,600 km perigee up to 1.5e8 km to the Sun).
 * Holding all of that in one coordinate system wrecks depth precision, so each
 * act gets a comfortable scale and the handovers hide behind a cross-fade timed
 * to land when Earth is about the same apparent size in both.
 *
 * The camera is framing-driven rather than position-driven: every act says how
 * many world units it needs to see and the distance falls out of the field of
 * view and the aspect ratio. That keeps the subject filling the frame at any
 * window size, which hand-tuned camera distances never manage.
 *
 * Every path drawn here is real. src/mission-data.json is generated by
 * tools/compute_mission.py from the same orbits, Lambert arc and corrected halo
 * the writeup describes. Nothing is drawn freehand.
 */

import {
  Scene, PerspectiveCamera, WebGLRenderer, Group, Vector3,
  BufferGeometry, BufferAttribute, Float32BufferAttribute,
  Line, LineBasicMaterial, LineSegments,
  Points, PointsMaterial,
  Sprite, SpriteMaterial, CanvasTexture, AdditiveBlending,
  Mesh, SphereGeometry, MeshBasicMaterial, RingGeometry, DoubleSide,
  MathUtils
} from 'three';

import DATA from './mission-data.json';

const ACCENT = 0x52d6e8;
const AMBER  = 0xff9e4a;
const SLATE  = 0x5c6b88;
const PALE   = 0xe8edf7;

// ONE world scale for all three acts: 1 unit = 100,000 km.
//
// Each act used to have its own, which kept the numbers comfortable but made
// the cross-fades incoherent: while two acts are both on screen the camera can
// only be positioned in one act's units, so the other renders at ten times the
// wrong size. Sharing a scale and translating each act's group into its real
// place means any two acts can be shown together and simply agree. Depth
// precision, the original reason for per-act scales, is handled by setting the
// near and far planes from the camera distance every frame instead.
const WORLD = 1e5;
const S1 = WORLD, S2 = WORLD, S3 = WORLD;

const M = DATA.meta;

/* ------------------------------------------------------------------ timing */
const ACTS = [
  { id: 'slingshot', label: 'Slingshot',      t0: 0,    t1: 15.5 },
  { id: 'cruise',    label: 'Cruise to L1',   t0: 15.5, t1: 29   },
  { id: 'halo',      label: 'Halo insertion', t0: 29,   t1: 44   }
];
const DUR = ACTS[ACTS.length - 1].t1;

const A1_INTRO = 1.3;
// The five orbits do not get equal time. Their real periods run from about
// 7.6 hours to 44, and giving the big ones a little longer stops the last two
// feeling rushed while keeping the whole act the same length.
const A1_W = (() => {
  const weight = [0.84, 0.88, 1.0, 1.12, 1.16];
  const total = 10.25;
  const sum = weight.reduce((a, b) => a + b, 0);
  const out = [];
  let t = A1_INTRO;
  for (const w of weight) { const d = total * w / sum; out.push([t, t + d]); t += d; }
  return out;
})();
const A1_ESC0 = A1_W[4][1];
const A1_ESC1 = ACTS[0].t1;

const smooth = (x) => x * x * (3 - 2 * x);
const clamp01 = (x) => (x < 0 ? 0 : x > 1 ? 1 : x);
const span = (t, a, b) => clamp01((t - a) / (b - a));

/** Piecewise interpolation over [time, value] keyframes, smoothed. */
function track(keys, t) {
  if (t <= keys[0][0]) return keys[0][1];
  for (let i = 1; i < keys.length; i++) {
    if (t <= keys[i][0]) {
      const f = smooth(span(t, keys[i - 1][0], keys[i][0]));
      return MathUtils.lerp(keys[i - 1][1], keys[i][1], f);
    }
  }
  return keys[keys.length - 1][1];
}

/* ------------------------------------------------------------- scene setup */
const host = document.getElementById('stage');
const reduce = window.matchMedia('(prefers-reduced-motion: reduce)').matches;

const scene = new Scene();

// The trajectory data uses the astrodynamics convention, z out of the orbital
// plane. Three.js takes y as up. Without this the ecliptic renders as a
// VERTICAL plane and every camera elevation rotates about the wrong axis.
const world = new Group();
world.rotation.x = -Math.PI / 2;
scene.add(world);

/** Data-space (already divided by its act scale) into world space. */
const toWorld = (v) => new Vector3(v.x, v.z, -v.y);

const camera = new PerspectiveCamera(42, 16 / 9, 0.02, 40000);
const renderer = new WebGLRenderer({ antialias: true, alpha: true, powerPreference: 'high-performance' });
renderer.setClearColor(0x000000, 0);
host.appendChild(renderer.domElement);

function resize() {
  const w = host.clientWidth || 800;
  const h = host.clientHeight || 450;
  renderer.setPixelRatio(Math.min(window.devicePixelRatio || 1, 1.8));
  renderer.setSize(w, h, false);
  camera.aspect = w / h;
  camera.updateProjectionMatrix();
}
window.addEventListener('resize', resize, { passive: true });

/** Camera distance at which a sphere of this radius just fills the frame. */
function fitDistance(radius) {
  const tv = Math.tan(MathUtils.degToRad(camera.fov) / 2);
  return radius / Math.min(tv, tv * camera.aspect);
}

/* --------------------------------------------------------------- utilities */
function polyline(pts, scale, color, opacity) {
  const g = new BufferGeometry();
  const a = new Float32Array(pts.length * 3);
  for (let i = 0; i < pts.length; i++) {
    a[i * 3] = pts[i][0] / scale;
    a[i * 3 + 1] = pts[i][1] / scale;
    a[i * 3 + 2] = pts[i][2] / scale;
  }
  g.setAttribute('position', new BufferAttribute(a, 3));
  const line = new Line(g, new LineBasicMaterial({ color, transparent: true, opacity }));
  line.frustumCulled = false;
  return line;
}

/** Cumulative arc length along a polyline, for speed warping. */
function arcTable(pts, scale) {
  const cum = [0];
  for (let i = 1; i < pts.length; i++) {
    cum.push(cum[i - 1] + Math.hypot(
      (pts[i][0] - pts[i - 1][0]) / scale,
      (pts[i][1] - pts[i - 1][1]) / scale,
      (pts[i][2] - pts[i - 1][2]) / scale));
  }
  return { cum, L: cum[cum.length - 1] };
}

/** Fractional index at an absolute arc length along the polyline. */
function fracIndexAtLength(tab, L) {
  const target = MathUtils.clamp(L, 0, tab.L);
  let lo = 0, hi = tab.cum.length - 1;
  while (lo < hi) { const mid = (lo + hi) >> 1; if (tab.cum[mid] < target) lo = mid + 1; else hi = mid; }
  if (lo === 0) return 0;
  const a = tab.cum[lo - 1], b = tab.cum[lo];
  return (lo - 1) + (b > a ? (target - a) / (b - a) : 0);
}

/** Overwrite one vertex of a drawn polyline with an interpolated source point.
 *
 * A draw range can only start and end on whole vertices, so a moving window
 * over a coarse polyline makes both ends jump a full sample at a time -- on the
 * transfer arc that is 680,000 km per step, most of the frame early in the
 * cruise, and it reads as the line juddering. Writing the two end vertices
 * explicitly each frame pins them to exactly where they belong. The buffer is
 * rewritten from the source data every frame, so clobbering a vertex is safe.
 */
function pinVertex(line, pts, scale, vertexIndex, sourceIndex) {
  const p = at(pts, scale, sourceIndex);
  const a = line.geometry.getAttribute('position');
  a.setXYZ(vertexIndex, p.x, p.y, p.z);
  a.needsUpdate = true;
}

/** Draw a window of a polyline, with both ends landing exactly where asked. */
function drawWindow(line, pts, tab, scale, headIdx, trailLen) {
  const headLen = tab.cum[MathUtils.clamp(Math.floor(headIdx), 0, tab.cum.length - 1)];
  const fromF = fracIndexAtLength(tab, headLen - trailLen);
  const from = Math.floor(fromF);
  const to = Math.min(Math.ceil(headIdx), pts.length - 1);
  if (to <= from) { line.geometry.setDrawRange(0, 0); return; }
  pinVertex(line, pts, scale, from, fromF);
  pinVertex(line, pts, scale, to, headIdx);
  line.geometry.setDrawRange(from, to - from + 1);
}

/** Index at a given fraction of total arc length (binary search). */
function indexAtArc(tab, u) {
  const target = u * tab.L;
  let lo = 0, hi = tab.cum.length - 1;
  while (lo < hi) { const mid = (lo + hi) >> 1; if (tab.cum[mid] < target) lo = mid + 1; else hi = mid; }
  return lo;
}

/** Fractional index at normalised time u, from the stored timestamps. */
function indexAtTime(tn, u) {
  let lo = 0, hi = tn.length - 1;
  while (lo < hi) { const mid = (lo + hi) >> 1; if (tn[mid] < u) lo = mid + 1; else hi = mid; }
  if (lo === 0) return 0;
  const a = tn[lo - 1], b = tn[lo];
  return (lo - 1) + (b > a ? (u - a) / (b - a) : 0);
}

// These orbits are extremely eccentric: the last one runs from a 6,613 km
// perigee out to 128,351 km, and the craft covers half its orbit in a sliver of
// the period. Animated at the physically correct speed it crosses perigee
// between two frames, which reads as a glitch rather than as speed. The index
// is therefore blended toward constant screen speed: perigee stays visibly the
// fast part, but it happens over frames a viewer can follow.
const SPEED_BLEND = 0.75;
function warpedIndex(tn, tab, u) {
  return MathUtils.lerp(indexAtTime(tn, u), indexAtArc(tab, u), SPEED_BLEND);
}

function at(pts, scale, i) {
  // Interpolated, not rounded. Snapping to the nearest sample makes the craft
  // advance in visible steps whenever the polyline is coarse relative to the
  // frame, which it is at the start of the heliocentric leg.
  const c = MathUtils.clamp(i, 0, pts.length - 1);
  const k = Math.floor(c), f = c - k, k2 = Math.min(k + 1, pts.length - 1);
  return new Vector3(
    MathUtils.lerp(pts[k][0], pts[k2][0], f) / scale,
    MathUtils.lerp(pts[k][1], pts[k2][1], f) / scale,
    MathUtils.lerp(pts[k][2], pts[k2][2], f) / scale
  );
}

/** Soft round dot, used for every marker and glow. */
const DOT = (() => {
  const c = document.createElement('canvas');
  c.width = c.height = 64;
  const g = c.getContext('2d').createRadialGradient(32, 32, 0, 32, 32, 32);
  g.addColorStop(0, 'rgba(255,255,255,1)');
  g.addColorStop(0.35, 'rgba(255,255,255,0.85)');
  g.addColorStop(1, 'rgba(255,255,255,0)');
  const ctx = c.getContext('2d');
  ctx.fillStyle = g;
  ctx.fillRect(0, 0, 64, 64);
  return new CanvasTexture(c);
})();

/** A marker that keeps the same size on screen no matter how far the camera is. */
function dot(color, size, opacity = 1, additive = false) {
  const s = new Sprite(new SpriteMaterial({
    map: DOT, color, transparent: true, opacity,
    sizeAttenuation: false, depthWrite: false,
    blending: additive ? AdditiveBlending : undefined
  }));
  s.scale.setScalar(size);
  s.userData.size = size;
  return s;
}

function ball(r, color, opacity = 1) {
  return new Mesh(new SphereGeometry(r, 24, 16),
    new MeshBasicMaterial({ color, transparent: true, opacity }));
}

function wireGlobe(r, color, opacity) {
  const pos = [];
  const push = (a, b) => { pos.push(a.x, a.y, a.z, b.x, b.y, b.z); };
  for (let k = -2; k <= 2; k++) {
    const lat = (k / 3) * Math.PI / 2, rr = r * Math.cos(lat), yy = r * Math.sin(lat);
    let prev = null;
    for (let i = 0; i <= 48; i++) {
      const a = (i / 48) * Math.PI * 2;
      const p = new Vector3(rr * Math.cos(a), yy, rr * Math.sin(a));
      if (prev) push(prev, p);
      prev = p;
    }
  }
  for (let j = 0; j < 6; j++) {
    const lon = (j / 6) * Math.PI;
    let prev = null;
    for (let i = 0; i <= 48; i++) {
      const a = (i / 48) * Math.PI * 2;
      const p = new Vector3(r * Math.cos(a) * Math.cos(lon), r * Math.sin(a), r * Math.cos(a) * Math.sin(lon));
      if (prev) push(prev, p);
      prev = p;
    }
  }
  const g = new BufferGeometry();
  g.setAttribute('position', new Float32BufferAttribute(pos, 3));
  return new LineSegments(g, new LineBasicMaterial({ color, transparent: true, opacity }));
}

function markBase(group) {
  group.traverse((c) => { if (c.material) { c.material.transparent = true; c.userData.base = c.material.opacity; } });
}
function setFade(group, o) {
  group.visible = o > 0.001;
  if (!group.visible) return;
  group.traverse((c) => { if (c.material && c.userData.base !== undefined) c.material.opacity = c.userData.base * o; });
}

/* ------------------------------------------------------------- star field */
{
  const n = 800, a = new Float32Array(n * 3);
  for (let i = 0; i < n; i++) {
    const r = 600 + Math.random() * 250;
    const th = Math.random() * Math.PI * 2, ph = Math.acos(2 * Math.random() - 1);
    a[i * 3] = r * Math.sin(ph) * Math.cos(th);
    a[i * 3 + 1] = r * Math.cos(ph);
    a[i * 3 + 2] = r * Math.sin(ph) * Math.sin(th);
  }
  const g = new BufferGeometry();
  g.setAttribute('position', new BufferAttribute(a, 3));
  const stars = new Points(g, new PointsMaterial({
    color: PALE, size: 1.8, sizeAttenuation: false, transparent: true, opacity: 0.5
  }));
  stars.frustumCulled = false;
  // Parented to the camera, so they behave as a backdrop at every zoom level.
  // Left in the scene they would sit at a fixed distance from the Sun and the
  // camera would fly through them during the wide shots.
  camera.add(stars);
  scene.add(camera);
}

/* ================================================================== act 1 */
const A1 = new Group();
// Earth-centred geometry, parked at Earth's position at the start of the
// transfer (the frame angle is zero there, so no rotation is needed).
A1.position.x = M.earthRotKm / WORLD;
world.add(A1);

const rE1 = M.earthRadiusKm / S1;
A1.add(ball(rE1, 0x0d2136, 1));
A1.add(wireGlobe(rE1, ACCENT, 0.55));

const raiseArcs = DATA.raises.map((r) => arcTable(r.pts, S1));
const escapeArc = arcTable(DATA.escape, S1);
const raiseLines = DATA.raises.map((r, i) =>
  polyline(r.pts, S1, i === 0 ? SLATE : ACCENT, i === 0 ? 0.5 : 0.75));
raiseLines.forEach((l) => { l.geometry.setDrawRange(0, 0); A1.add(l); });

const escLine = polyline(DATA.escape, S1, ACCENT, 0.95);
escLine.geometry.setDrawRange(0, 0);
A1.add(escLine);

const soiRing = new Mesh(
  new RingGeometry(M.soiKm / S1 * 0.997, M.soiKm / S1, 160),
  new MeshBasicMaterial({ color: SLATE, transparent: true, opacity: 0, side: DoubleSide })
);
soiRing.rotation.x = Math.PI / 2;
A1.add(soiRing);

const craft1 = dot(PALE, 0.016);
const burn1 = dot(AMBER, 0.05, 0, true);
A1.add(craft1, burn1);
markBase(A1);

/* ================================================================== act 2 */
const A2 = new Group();
world.add(A2);

// Neither body is to scale here; at this zoom the real Sun would be a pixel.
A2.add(dot(AMBER, 0.055, 0.95));
A2.add(dot(AMBER, 0.16, 0.20, true));
// The heliocentric leg was computed against a 1.496e8 km AU and the CR3BP
// against 149,597,870.7. Draw Earth at the CR3BP value in both acts so the two
// agree exactly at the handover; the 25,786 km that pushes into the transfer
// arc is 0.017% of this frame.
{ // full circle, not just the arc Earth covers during the transfer: at this
  // zoom the transfer arc and Earth's path differ by about 1%, so the partial
  // arc was invisible underneath it. The ring is what gives the scene scale.
  const ring = [];
  for (let i = 0; i <= 256; i++) {
    const a = (i / 256) * Math.PI * 2;
    ring.push([Math.cos(a) * M.earthRotKm, Math.sin(a) * M.earthRotKm, 0]);
  }
  A2.add(polyline(ring, S2, SLATE, 0.3));
}

const arcLine = polyline(DATA.transfer, S2, ACCENT, 0.95);
arcLine.geometry.setDrawRange(0, 0);
A2.add(arcLine);
const transferArc = arcTable(DATA.transfer, S2);

const earth2 = dot(0x6ba8e8, 0.022);
earth2.position.set(M.earthRotKm / S2, 0, 0);
const craft2 = dot(PALE, 0.014);
// L1 itself, so the dive at the end of the act closes on something rather than
// on empty space. It rides inside A2, so the de-spin carries it correctly.
const l1mark2 = dot(AMBER, 0.013, 0.85);
A2.add(earth2, craft2, l1mark2);
markBase(A2);

/* ================================================================== act 3 */
const A3 = new Group();
// L1-relative geometry, parked at L1 in the rotating frame that act 2 de-spins
// into, so the two coincide exactly through the handover.
A3.position.x = M.xL1Km / WORLD;
world.add(A3);

// L1 sits at the origin of act 3; Earth goes along +x at the real offset.
const dxEarth = (M.earthRotKm - M.xL1Km) / S3;
const rE3 = 0.62;
const earth3 = ball(rE3, 0x0d2136, 1);
earth3.position.x = dxEarth;
const earth3wire = wireGlobe(rE3, ACCENT, 0.4);
earth3wire.position.x = dxEarth;
A3.add(earth3, earth3wire);

{
  const g = new BufferGeometry();
  g.setAttribute('position', new Float32BufferAttribute([-30, 0, 0, dxEarth, 0, 0], 3));
  A3.add(new LineSegments(g, new LineBasicMaterial({ color: SLATE, transparent: true, opacity: 0.28 })));
  const s = 0.8, c = new BufferGeometry();
  c.setAttribute('position', new Float32BufferAttribute(
    [-s, 0, 0, s, 0, 0, 0, -s, 0, 0, s, 0, 0, 0, -s, 0, 0, s], 3));
  A3.add(new LineSegments(c, new LineBasicMaterial({ color: AMBER, transparent: true, opacity: 0.7 })));
}

const haloRel = DATA.halo.map((p) => [p[0] - M.xL1Km, p[1], p[2]]);
const haloArc = arcTable(haloRel, S3);
A3.add(polyline(haloRel, S3, SLATE, 0.2));
const haloLine = polyline(haloRel, S3, ACCENT, 0.95);
haloLine.geometry.setDrawRange(0, 0);
A3.add(haloLine);

// The last stretch of the cruise, de-spun into the rotating frame. Act 2 stops
// the craft here and act 3 picks it up at exactly this sample, so the handover
// continues the same journey instead of rewinding it.
const TAIL_N = 26;
const ARC_STOP = DATA.transfer.length - TAIL_N;   // index act 2 animates up to
const cosT = Math.cos(-M.thetaTransfer), sinT = Math.sin(-M.thetaTransfer);
const tailRel = DATA.transfer.slice(ARC_STOP).map((p) => [
  p[0] * cosT - p[1] * sinT - M.xL1Km,
  p[0] * sinT + p[1] * cosT,
  p[2]
]);
A3.add(polyline(tailRel, S3, ACCENT, 0.35));

const craft3 = dot(PALE, 0.014);
const burn3 = dot(AMBER, 0.05, 0, true);
A3.add(craft3, burn3);
markBase(A3);

/* --------------------------------------------------------------- captions */
const fmt = (n) => n.toLocaleString('en-US');
const CAPTIONS = [
  [0.0,          'Parking orbit',       '235 × 19,500 km, inclined 19.2°'],
  [A1_W[1][0],   'Burn 1 at perigee',   `apogee → ${fmt(M.raiseApogees[1])} km`],
  [A1_W[2][0],   'Burn 2 at perigee',   `apogee → ${fmt(M.raiseApogees[2])} km`],
  [A1_W[3][0],   'Burn 3 at perigee',   `apogee → ${fmt(M.raiseApogees[3])} km`],
  [A1_W[4][0],   'Burn 4 at perigee',   `apogee → ${fmt(M.raiseApogees[4])} km`],
  [A1_W[4][0] + 1.1, 'Coasting to perigee', 'the Oberth effect makes perigee the cheapest place to burn'],
  [A1_ESC0,      'Escape burn',         `${M.escapeDvMs} m/s, enough to leave Earth\u2019s sphere of influence`],
  [A1_ESC0 + 1.9, 'Crossing the sphere of influence',
                  `925,000 km, ${M.escapeDays.toFixed(1)} days after the burn`],
  [15.5,  'Now measured against the Sun',      'the spacecraft carries Earth’s 29.8 km/s with it'],
  [17.6,  'Lambert transfer arc',              '110 days from the sphere of influence to L1'],
  [21.0,  'Sun, Earth, spacecraft',            'the whole transfer in one frame'],
  [22.6,  'Locking to the rotating frame',     'Earth held fixed on the Sun-Earth line'],
  [26.4,  'Closing on L1',                     'the destination is 1.5 million km sunward of Earth'],
  [29.0,  'Arrival at L1',                     '1,491,551 km sunward of Earth'],
  [30.6,  'Insertion burn',                    '265 m/s onto the halo'],
  [32.6,  'Halo orbit',                        'A_z = 120,000 km, one lap every 177.9 days'],
  [39.5,  'The orbit is unstable',             'holding it costs 0.2 to 0.4 m/s of station-keeping']
];

const elPhase = document.getElementById('cap-phase');
const elNote = document.getElementById('cap-note');
const elClock = document.getElementById('clock');
let lastCap = -1;

function caption(t) {
  let i = 0;
  for (let k = 0; k < CAPTIONS.length; k++) if (t >= CAPTIONS[k][0]) i = k;
  if (i !== lastCap) {
    lastCap = i;
    elPhase.textContent = CAPTIONS[i][1];
    elNote.textContent = CAPTIONS[i][2];
  }
}

function missionDay(t) {
  if (t < A1_ESC0) return (t / A1_ESC0) * 4.6;   // the five orbits, ~4.6 days
  if (t < ACTS[0].t1) return 4.6 + span(t, A1_ESC0, ACTS[0].t1) * M.escapeDays;
  if (t < ACTS[1].t1) return 4.6 + M.escapeDays + span(t, ACTS[1].t0, ACTS[1].t1) * M.transferDays;
  return 4.6 + M.escapeDays + M.transferDays + span(t, ACTS[2].t0 + 1.6, ACTS[2].t1) * M.haloDays * 2;
}

/* ----------------------------------------------------------------- camera */
// What each act needs to hold in frame, in its own world units.
/** Centre and radius that just contain a polyline, in that act's world units. */
function bounds(pts, scale) {
  let lo = [Infinity, Infinity, Infinity], hi = [-Infinity, -Infinity, -Infinity];
  for (const p of pts) for (let i = 0; i < 3; i++) {
    if (p[i] < lo[i]) lo[i] = p[i];
    if (p[i] > hi[i]) hi[i] = p[i];
  }
  const c = new Vector3((lo[0] + hi[0]) / 2 / scale, (lo[1] + hi[1]) / 2 / scale, (lo[2] + hi[2]) / 2 / scale);
  let r = 0;
  for (const p of pts) {
    const d = Math.hypot(p[0] / scale - c.x, p[1] / scale - c.y, p[2] / scale - c.z);
    if (d > r) r = d;
  }
  return { c: toWorld(c), r };
}

/** Same as track(), for Vector3 keyframes. */
function trackVec(keys, t, out) {
  if (t <= keys[0][0]) return out.copy(keys[0][1]);
  for (let i = 1; i < keys.length; i++) {
    if (t <= keys[i][0]) {
      return out.copy(keys[i - 1][1]).lerp(keys[i][1], smooth(span(t, keys[i - 1][0], keys[i][0])));
    }
  }
  return out.copy(keys[keys.length - 1][1]);
}

/* --- one continuous camera, not three -------------------------------------
 * Each act used to own its framing, which meant the apparent scale and the
 * view direction both jumped at every handover. Everything below is defined
 * once across the whole timeline instead:
 *
 *   - the framing radius is in KILOMETRES and interpolated in log space, so a
 *     190x zoom-out reads as a steady dolly rather than a lurch, and the value
 *     either side of an act boundary is the same real distance;
 *   - azimuth and elevation are single continuous tracks, so the view direction
 *     never snaps;
 *   - at each boundary the camera targets Earth, which exists in both acts, so
 *     the cross-fade happens with the same object in the same place at the same
 *     size on screen.
 */
const T_HANDOVER_1 = ACTS[0].t1;    // Earth-centred -> heliocentric
const T_HANDOVER_2 = ACTS[1].t1;    // heliocentric -> rotating frame at L1
const R_HANDOVER_1 = M.soiKm * 1.15;         // km in frame at handover 1
const R_HANDOVER_2 = 2.0e6;                  // floor only; the approach rule wins

// Frame each raise on the ellipse itself rather than on Earth: an ellipse's far
// side is twice as far as its semi-major axis, so centring on Earth wastes half
// the frame.
const RB = DATA.raises.map((x) => bounds(x.pts, S1));
// Where act 1 leaves the spacecraft. Act 1 used to hand the camera over centred
// on Earth, which meant act 2 had to jump 925,000 km to pick the craft up.
const SOI_EXIT = toWorld(at(DATA.escape, S1, DATA.escape.length - 1));

// Framing radius in km, across the whole run.
const R_KM = (() => {
  const k = [[0, RB[0].r * S1 * 1.22]];
  for (let i = 0; i < 5; i++) k.push([A1_W[i][0] - 0.3, RB[i].r * S1 * 1.22]);
  k.push([A1_ESC0 - 0.2, RB[4].r * S1 * 1.22]);
  k.push([T_HANDOVER_1, R_HANDOVER_1]);
  k.push([ACTS[1].t0 + 2.6, 6.5e6]);
  k.push([ACTS[1].t1 - 5.0, M.earthRotKm * 1.2]);
  k.push([ACTS[1].t1 - 2.6, M.earthRotKm * 1.2]);
  k.push([T_HANDOVER_2, R_HANDOVER_2]);
  k.push([ACTS[2].t0 + 4.2, 9.7e5]);
  k.push([ACTS[2].t0 + 5.4, 9.7e5]);
  k.push([ACTS[2].t1, 9.7e5]);
  return k;
})();

/** Log-space interpolation: constant zoom RATE rather than constant km/second. */
function radiusKm(t) {
  const k = R_KM;
  if (t <= k[0][0]) return k[0][1];
  for (let i = 1; i < k.length; i++) {
    if (t <= k[i][0]) {
      const f = smooth(span(t, k[i - 1][0], k[i][0]));
      return Math.exp(MathUtils.lerp(Math.log(k[i - 1][1]), Math.log(k[i][1]), f));
    }
  }
  return k[k.length - 1][1];
}

const AZ_KEYS = [
  [0, 0.55], [A1_ESC0, 1.35], [T_HANDOVER_1, 1.55],
  [ACTS[1].t0 + 5.5, 1.08], [ACTS[1].t1 - 4.6, 0.42],
  [T_HANDOVER_2, 0.05], [ACTS[2].t0 + 5, -0.42], [ACTS[2].t1, -0.72]
];
const EL_KEYS = [
  [0, 0.5], [A1_ESC0, 0.3], [T_HANDOVER_1, 0.28],
  [ACTS[1].t0 + 5, 0.5], [ACTS[1].t1 - 4.6, 0.66],
  [T_HANDOVER_2, 0.44], [ACTS[2].t0 + 5, 0.3], [ACTS[2].t1, 0.4]
];

// The halo loop lies roughly in the plane normal to the Sun-Earth line, so the
// view settles about 35 degrees off that line: enough to open the loop out
// without putting Earth behind the camera.
const A3_TARGET_X = dxEarth * 0.46;

/* The approach to L1 is wildly non-linear: the spacecraft is still 17 million km
 * out at 94% of the arc and covers the last 3 million in the final one percent.
 * No fixed zoom schedule can follow that, so through the arrival the framing
 * radius is driven by the actual distance left to run and the schedule acts
 * only as a floor. The zoom then tracks the approach by construction, and the
 * radius is continuous across the handover because the craft's position is.
 */
const APPROACH_MARGIN = 1.45;

function frameRadiusKm(t) {
  const scheduled = radiusKm(t);
  if (t >= ACTS[1].t1 - 3.2 && t < T_HANDOVER_2) {
    craft2.getWorldPosition(tmpA);
    l1mark2.getWorldPosition(tmpB);
    return Math.max(scheduled, tmpA.distanceTo(tmpB) * WORLD * APPROACH_MARGIN);
  }
  if (t >= T_HANDOVER_2 && t < ACTS[2].t0 + 4.2) {
    craft3.getWorldPosition(tmpA).sub(A3.position);     // distance from L1
    return Math.max(scheduled, tmpA.length() * WORLD * APPROACH_MARGIN);
  }
  return scheduled;
}

const camPos = new Vector3();
const camTgt = new Vector3();
const tmpA = new Vector3();
const tmpB = new Vector3();
const tmpE = new Vector3();
const tmpV = new Vector3();
const tmpW = new Vector3();
const ORIGIN = new Vector3(0, 0, 0);
const orbit = (az, el, d, out) =>
  out.set(Math.cos(az) * Math.cos(el) * d, Math.sin(el) * d, Math.sin(az) * Math.cos(el) * d);

function placeCamera(t) {
  if (t < T_HANDOVER_1) {
    // Early on, frame each ellipse on itself; by the escape, on Earth, which is
    // the anchor the next act has to match.
    trackVec(
      [[0, RB[0].c], ...RB.map((b, i) => [A1_W[i][0] - 0.3, b.c]),
       [A1_ESC0 - 0.2, RB[4].c], [T_HANDOVER_1, SOI_EXIT]],
      t, camTgt
    );
    camTgt.add(A1.position);   // act 1 rides with Earth; read it, do not assume
  } else if (t < T_HANDOVER_2) {
    scale = S2;
    // Earth, then the Sun, then the spacecraft. Diving toward Earth instead
    // loses the craft off the edge of the frame: it is still most of the way
    // from Earth to L1 while the zoom is already tightening.
    // Earth -> the Sun-Earth midpoint -> the spacecraft, as sequential lerps.
    // Two things this must not do: run the target to the Sun (the craft then
    // sits 150 million km outside a frame that has not widened yet, and
    // vanishes for five seconds), or scale one vector toward the origin, which
    // walks the target down the Sun line rather than between two points. The
    // pan only starts once the frame is wide enough to keep the craft inside.
    // Spacecraft -> Earth -> the Sun-Earth midpoint -> spacecraft again.
    // It opens on the craft because that is exactly where act 1 left the camera,
    // and because the point of this beat is that the craft is already on a solar
    // orbit: hold on it, rotate slowly and pull back, and the new orbit reveals
    // itself around it.
    const settle = smooth(span(t, ACTS[1].t0 + 1.2, ACTS[1].t0 + 5.5));
    const away = smooth(span(t, ACTS[1].t1 - 8.0, ACTS[1].t1 - 5.0));
    const back = smooth(span(t, ACTS[1].t1 - 4.0, ACTS[1].t1 - 2.6));
    earth2.getWorldPosition(tmpV);
    craft2.getWorldPosition(tmpW);
    camTgt.copy(tmpW).lerp(tmpV, settle).lerp(ORIGIN, away * 0.5).lerp(tmpW, back);
  } else {
    // Opens on the spacecraft, which is exactly where act 2 left it, then
    // slides to sit between Earth and L1 once the halo is the subject.
    const f = smooth(span(t, ACTS[2].t0, ACTS[2].t0 + 4.2));
    craft3.getWorldPosition(tmpW);
    camTgt.set(A3_TARGET_X, 0, 0).add(A3.position).lerp(tmpW, 1 - f);
  }

  const dist = fitDistance(frameRadiusKm(t) / WORLD);
  orbit(track(AZ_KEYS, t), track(EL_KEYS, t), dist, camPos);
  camPos.add(camTgt);

  // Depth range follows the zoom. One fixed pair of planes cannot serve a view
  // that ranges from 3,000 km across to 300 million.
  camera.near = Math.max(dist * 0.004, 0.0005);
  camera.far = Math.max(dist * 60, 4000);
  camera.updateProjectionMatrix();
}

/* ----------------------------------------------------------------- update */
const nR = DATA.raises.map((r) => r.pts.length);
const nEsc = DATA.escape.length;
const nArc = DATA.transfer.length;
const nHalo = DATA.halo.length;

function flash(sprite, amount, base) {
  sprite.material.opacity = amount * 0.95 * base;
  sprite.scale.setScalar(sprite.userData.size * (0.7 + (1 - amount) * 1.6));
}

function update(t) {
  caption(t);
  elClock.textContent = `T + ${missionDay(t).toFixed(1)} d`;

  /* ---- act 1 */
  const a1 = 1 - span(t, ACTS[0].t1 - 0.15, ACTS[0].t1 + 0.5);
  setFade(A1, a1);
  if (a1 > 0) {
    let burn = 0;
    for (let k = 0; k < 5; k++) {
      const f = span(t, A1_W[k][0], A1_W[k][1]);
      const idx = warpedIndex(DATA.raises[k].tn, raiseArcs[k], f);
      if (f <= 0) raiseLines[k].geometry.setDrawRange(0, 0);
      else drawWindow(raiseLines[k], DATA.raises[k].pts, raiseArcs[k], S1, idx, raiseArcs[k].L);
      if (f > 0 && f < 1) {
        craft1.position.copy(at(DATA.raises[k].pts, S1, idx));
        if (k > 0 && f < 0.12) burn = 1 - f / 0.12;
      }
    }
    if (t < A1_INTRO) craft1.position.copy(at(DATA.raises[0].pts, S1, 0));

    const fe = span(t, A1_ESC0, A1_ESC1);
    const ie = warpedIndex(DATA.escapeTn, escapeArc, fe);
    if (fe <= 0) escLine.geometry.setDrawRange(0, 0);
    else drawWindow(escLine, DATA.escape, escapeArc, S1, ie, escapeArc.L);
    if (fe > 0) {
      craft1.position.copy(at(DATA.escape, S1, ie));
      if (fe < 0.1) burn = Math.max(burn, 1 - fe / 0.1);
    }
    burn1.position.copy(craft1.position);
    flash(burn1, burn, a1);
    soiRing.material.opacity = 0.28 * span(t, A1_ESC0 + 1.0, A1_ESC1) * a1;
  }

  /* ---- act 2 */
  const a2 = Math.min(span(t, ACTS[0].t1 - 0.7, ACTS[0].t1 + 0.5),
                      1 - span(t, ACTS[1].t1 - 0.3, ACTS[1].t1 + 0.8));
  setFade(A2, a2);
  {
    // Earth and L1 are placed every frame, whether or not act 2 is being drawn,
    // because act 1 is pinned to Earth and needs to know where it is.
    const f = span(t, ACTS[1].t0, ACTS[1].t1);
    const th = f * M.thetaTransfer;
    earth2.position.set(Math.cos(th) * M.earthRotKm / S2, Math.sin(th) * M.earthRotKm / S2, 0);
    l1mark2.position.set(Math.cos(th) * M.xL1Km / S2, Math.sin(th) * M.xL1Km / S2, 0);

    // Act 1's geometry is Earth-relative, so it has to ride with Earth. Left at
    // a fixed heliocentric position it gets abandoned the moment act 2 starts
    // advancing: Earth covers 10 million km during the half-second cross-fade
    // and the frame is only 1 million km across, so everything from act 1
    // appears to shoot sideways out of shot.
    earth2.getWorldPosition(tmpE);
    world.worldToLocal(tmpE);
    A1.position.copy(tmpE);
  }
  if (a2 > 0) {
    const f = span(t, ACTS[1].t0, ACTS[1].t1);
    const head = f * ARC_STOP;
    craft2.position.copy(at(DATA.transfer, S2, head));

    // The arc is drawn as a trail growing out of the spacecraft rather than as
    // the whole path from its start. Early in the act the camera is only about
    // a million km wide while the arc already begins tens of millions of km
    // back, so drawing from index 0 put a hard straight line across the frame
    // and out of the corner. The trail is capped to a length the current frame
    // can actually show, and opens up on its own as the camera pulls back.
    // Capped to what the frame can show early on, then released as the camera
    // pulls back so the wide shot really does hold the whole transfer.
    const cap = 0.85 * frameRadiusKm(t) / WORLD;
    const opened = transferArc.L * smooth(span(t, ACTS[1].t0 + 6, ACTS[1].t1 - 7));
    drawWindow(arcLine, DATA.transfer, transferArc, S2, head, Math.max(cap, opened));

    // The arc fades in after act 1 has gone. Act 1's trail is measured against
    // EARTH and this one against the SUN, so near the crossing they leave the
    // craft at very different angles -- both correct, but drawn together they
    // look like a broken path. Showing one at a time makes the change of frame
    // the point rather than an artefact.
    arcLine.material.opacity = arcLine.userData.base * a2 *
      smooth(span(t, ACTS[1].t0 + 0.45, ACTS[1].t0 + 1.7));
    // De-spin at the end of the act, so the frame hands over already locked to
    // the Sun-Earth line that act 3 works in.
    A2.rotation.z = -M.thetaTransfer * f * smooth(span(t, ACTS[1].t1 - 6.5, ACTS[1].t1 - 3.8));
  }

  /* ---- act 3 */
  const a3 = span(t, ACTS[1].t1 - 0.6, ACTS[1].t1 + 0.6);
  setFade(A3, a3);
  if (a3 > 0) {
    const arrive = span(t, ACTS[2].t0, ACTS[2].t0 + 1.6);
    const g = span(t, ACTS[2].t0 + 1.6, ACTS[2].t1);
    const laps = 2;
    if (g <= 0) {
      haloLine.geometry.setDrawRange(0, 0);
      craft3.position.copy(at(tailRel, S3, arrive * (tailRel.length - 1)));
    } else {
      const hi = Math.min(1, g * laps) * (nHalo - 1);
      drawWindow(haloLine, haloRel, haloArc, S3, hi, haloArc.L);
      craft3.position.copy(at(haloRel, S3, (g * laps * (nHalo - 1)) % (nHalo - 1)));
    }
    burn3.position.copy(craft3.position);
    flash(burn3, 1 - clamp01(Math.abs(t - (ACTS[2].t0 + 1.6)) / 0.5), a3);
  }

  // Exactly one spacecraft on screen. Act 1's craft and act 2's differ by the
  // 25,786 km between the two source AU values, which is small but enough to
  // read as a second craft while both acts are drawn. Hand over at the midpoint
  // of the fade, where the two are effectively in the same place.
  if (a1 > 0 && a2 > 0) {
    const useSecond = a1 < 0.5;
    craft1.material.opacity = useSecond ? 0 : craft1.userData.base * a1;
    burn1.material.opacity = useSecond ? 0 : burn1.material.opacity;
    craft2.material.opacity = useSecond ? craft2.userData.base * a2 : 0;
  }

  placeCamera(t);
  camera.position.copy(camPos);
  camera.lookAt(camTgt);
}

/* -------------------------------------------------------------- transport */
let time = 0, playing = false, last = 0, allowed = true;

const btn = document.getElementById('play');
const bar = document.getElementById('bar');
const fill = document.getElementById('fill');
const chapEls = Array.from(document.querySelectorAll('.chap'));

function setPlaying(v) {
  playing = v && allowed && !reduce;
  btn.setAttribute('aria-label', playing ? 'Pause' : 'Play');
  btn.dataset.state = playing ? 'playing' : 'paused';
}

function paint() {
  fill.style.width = (time / DUR * 100).toFixed(2) + '%';
  bar.setAttribute('aria-valuenow', time.toFixed(1));
  let act = 0;
  for (let i = 0; i < ACTS.length; i++) if (time >= ACTS[i].t0) act = i;
  chapEls.forEach((c, i) => c.classList.toggle('on', i === act));
}

function seek(t) {
  time = MathUtils.clamp(t, 0, DUR);
  update(time);
  paint();
}

btn.addEventListener('click', () => {
  if (time >= DUR - 0.01) { seek(0); setPlaying(true); return; }
  setPlaying(!playing);
});
/* --------------------------------------------------- deep links to chapters */
// viewer/#halo opens on that act. The writeup links straight to the part it is
// discussing, and a chapter can be shared on its own.
function chapterFromHash() {
  return ACTS.findIndex((a) => a.id === (location.hash || '').replace('#', ''));
}

chapEls.forEach((c, i) => c.addEventListener('click', () => {
  seek(ACTS[i].t0 + 0.02);
  setPlaying(true);
  // replaceState, not a new entry: chapter buttons should not fill the back button.
  try { history.replaceState(null, '', '#' + ACTS[i].id); } catch (e) { /* file:// */ }
}));

window.addEventListener('hashchange', () => {
  const i = chapterFromHash();
  if (i >= 0) { seek(ACTS[i].t0 + 0.02); setPlaying(true); }
});

function scrubFrom(e) {
  const r = bar.getBoundingClientRect();
  seek(clamp01((e.clientX - r.left) / r.width) * DUR);
}
let scrubbing = false;
bar.addEventListener('pointerdown', (e) => { scrubbing = true; bar.setPointerCapture(e.pointerId); scrubFrom(e); });
bar.addEventListener('pointermove', (e) => { if (scrubbing) scrubFrom(e); });
bar.addEventListener('pointerup', (e) => { scrubbing = false; try { bar.releasePointerCapture(e.pointerId); } catch (_) {} });
bar.addEventListener('keydown', (e) => {
  if (e.key === 'ArrowRight') { seek(time + 1); e.preventDefault(); }
  if (e.key === 'ArrowLeft') { seek(time - 1); e.preventDefault(); }
  if (e.key === ' ' || e.key === 'Enter') { setPlaying(!playing); e.preventDefault(); }
});

/* --------------------------------------------- visibility, in page and out */
// Inside an iframe an IntersectionObserver only sees the iframe's own viewport,
// so the parent tells us when the embed is actually on screen. Standalone, no
// message ever arrives and we simply play.
let heardFromParent = false;
window.addEventListener('message', (e) => {
  if (!e.data || e.data.type !== 'viewer-visibility') return;
  heardFromParent = true;
  allowed = !!e.data.visible;
  if (!allowed) setPlaying(false);
  else if (time < DUR - 0.01) setPlaying(true);
});

document.addEventListener('visibilitychange', () => {
  if (document.hidden) setPlaying(false);
  else if (allowed && time < DUR - 0.01) setPlaying(true);
});

/* -------------------------------------------------------------------- loop */
function frame(now) {
  requestAnimationFrame(frame);
  const dt = Math.min((now - last) / 1000, 0.05);
  last = now;
  if (playing) {
    time += dt;
    if (time >= DUR) { time = DUR; setPlaying(false); }
    update(time);
    paint();
  }
  renderer.render(scene, camera);
}

resize();
update(0);
paint();
setPlaying(false);
requestAnimationFrame((n) => { last = n; frame(n); });

const startChapter = chapterFromHash();
if (startChapter > 0) seek(ACTS[startChapter].t0 + 0.02);

if (reduce) {
  seek(ACTS[2].t0 + 8);
  document.getElementById('shell').classList.add('static');
} else {
  setTimeout(() => { if (!heardFromParent) { allowed = true; setPlaying(true); } }, 800);
}

window.__viewer = {
  seek, resize, DUR, ACTS,
  get time() { return time; },
  get playing() { return playing; },
  // Small probe so the motion can be checked numerically rather than by eye.
  probe() {
    const craft = time < ACTS[0].t1 ? craft1 : time < ACTS[1].t1 ? craft2 : craft3;
    // seek() does not render, so the camera's inverse matrix would otherwise be
    // whatever the last painted frame left behind.
    camera.updateMatrixWorld(true);
    camera.matrixWorldInverse.copy(camera.matrixWorld).invert();
    const w = craft.getWorldPosition(new Vector3());
    const screen = w.clone().project(camera);
    return {
      camX: camera.position.x, camY: camera.position.y, camZ: camera.position.z,
      tgtX: camTgt.x, tgtY: camTgt.y, tgtZ: camTgt.z,
      radiusKm: frameRadiusKm(time),
      cwX: w.x, cwY: w.y, cwZ: w.z,
      sx: screen.x, sy: screen.y
    };
  }
};
