/* Mission viewer for the L1 project page.
 *
 * Three acts, each rendered in its own unit system because the scales involved
 * span five orders of magnitude (a 6,600 km perigee up to 1.5e8 km to the Sun).
 * Holding all of that in one coordinate system wrecks depth precision, so each
 * act gets a comfortable scale and the handovers hide behind a cross-fade timed
 * to land when Earth is about the same apparent size in both.
 *
 * The camera is framing-driven rather than position-driven: every act says how
 * many world units it needs to see and the distance falls out of the field of
 * view and the aspect ratio. That keeps the subject filling the frame at any
 * window size, which hand-tuned camera distances never manage.
 *
 * Every path drawn here is real. src/mission-data.json is generated by
 * tools/compute_mission.py from the same orbits, Lambert arc and corrected halo
 * the writeup describes. Nothing is drawn freehand.
 */

import {
  Scene, PerspectiveCamera, WebGLRenderer, Group, Vector3,
  BufferGeometry, BufferAttribute, Float32BufferAttribute,
  Line, LineBasicMaterial, LineSegments,
  Points, PointsMaterial,
  Sprite, SpriteMaterial, CanvasTexture, AdditiveBlending,
  Mesh, SphereGeometry, MeshBasicMaterial, RingGeometry, DoubleSide,
  MathUtils
} from 'three';

import DATA from './mission-data.json';

const ACCENT = 0x52d6e8;
const AMBER  = 0xff9e4a;
const SLATE  = 0x5c6b88;
const PALE   = 0xe8edf7;

// 1 world unit equals this many km, per act.
const S1 = 1e4;   // act 1: Earth neighbourhood
const S2 = 1e6;   // act 2: heliocentric
const S3 = 1e5;   // act 3: around L1

const M = DATA.meta;

/* ------------------------------------------------------------------ timing */
const ACTS = [
  { id: 'slingshot', label: 'Slingshot',      t0: 0,    t1: 15.5 },
  { id: 'cruise',    label: 'Cruise to L1',   t0: 15.5, t1: 29   },
  { id: 'halo',      label: 'Halo insertion', t0: 29,   t1: 44   }
];
const DUR = ACTS[ACTS.length - 1].t1;

const A1_INTRO = 1.3;
const A1_ORBIT = 2.05;
const A1_ESC0  = A1_INTRO + 5 * A1_ORBIT;   // 11.55
const A1_ESC1  = ACTS[0].t1;

const smooth = (x) => x * x * (3 - 2 * x);
const clamp01 = (x) => (x < 0 ? 0 : x > 1 ? 1 : x);
const span = (t, a, b) => clamp01((t - a) / (b - a));

/** Piecewise interpolation over [time, value] keyframes, smoothed. */
function track(keys, t) {
  if (t <= keys[0][0]) return keys[0][1];
  for (let i = 1; i < keys.length; i++) {
    if (t <= keys[i][0]) {
      const f = smooth(span(t, keys[i - 1][0], keys[i][0]));
      return MathUtils.lerp(keys[i - 1][1], keys[i][1], f);
    }
  }
  return keys[keys.length - 1][1];
}

/* ------------------------------------------------------------- scene setup */
const host = document.getElementById('stage');
const reduce = window.matchMedia('(prefers-reduced-motion: reduce)').matches;

const scene = new Scene();

// The trajectory data uses the astrodynamics convention, z out of the orbital
// plane. Three.js takes y as up. Without this the ecliptic renders as a
// VERTICAL plane and every camera elevation rotates about the wrong axis.
const world = new Group();
world.rotation.x = -Math.PI / 2;
scene.add(world);

/** Data-space (already divided by its act scale) into world space. */
const toWorld = (v) => new Vector3(v.x, v.z, -v.y);

const camera = new PerspectiveCamera(42, 16 / 9, 0.02, 40000);
const renderer = new WebGLRenderer({ antialias: true, alpha: true, powerPreference: 'high-performance' });
renderer.setClearColor(0x000000, 0);
host.appendChild(renderer.domElement);

function resize() {
  const w = host.clientWidth || 800;
  const h = host.clientHeight || 450;
  renderer.setPixelRatio(Math.min(window.devicePixelRatio || 1, 1.8));
  renderer.setSize(w, h, false);
  camera.aspect = w / h;
  camera.updateProjectionMatrix();
}
window.addEventListener('resize', resize, { passive: true });

/** Camera distance at which a sphere of this radius just fills the frame. */
function fitDistance(radius) {
  const tv = Math.tan(MathUtils.degToRad(camera.fov) / 2);
  return radius / Math.min(tv, tv * camera.aspect);
}

/* --------------------------------------------------------------- utilities */
function polyline(pts, scale, color, opacity) {
  const g = new BufferGeometry();
  const a = new Float32Array(pts.length * 3);
  for (let i = 0; i < pts.length; i++) {
    a[i * 3] = pts[i][0] / scale;
    a[i * 3 + 1] = pts[i][1] / scale;
    a[i * 3 + 2] = pts[i][2] / scale;
  }
  g.setAttribute('position', new BufferAttribute(a, 3));
  const line = new Line(g, new LineBasicMaterial({ color, transparent: true, opacity }));
  line.frustumCulled = false;
  return line;
}

function at(pts, scale, i) {
  const k = MathUtils.clamp(Math.round(i), 0, pts.length - 1);
  return new Vector3(pts[k][0] / scale, pts[k][1] / scale, pts[k][2] / scale);
}

/** Soft round dot, used for every marker and glow. */
const DOT = (() => {
  const c = document.createElement('canvas');
  c.width = c.height = 64;
  const g = c.getContext('2d').createRadialGradient(32, 32, 0, 32, 32, 32);
  g.addColorStop(0, 'rgba(255,255,255,1)');
  g.addColorStop(0.35, 'rgba(255,255,255,0.85)');
  g.addColorStop(1, 'rgba(255,255,255,0)');
  const ctx = c.getContext('2d');
  ctx.fillStyle = g;
  ctx.fillRect(0, 0, 64, 64);
  return new CanvasTexture(c);
})();

/** A marker that keeps the same size on screen no matter how far the camera is. */
function dot(color, size, opacity = 1, additive = false) {
  const s = new Sprite(new SpriteMaterial({
    map: DOT, color, transparent: true, opacity,
    sizeAttenuation: false, depthWrite: false,
    blending: additive ? AdditiveBlending : undefined
  }));
  s.scale.setScalar(size);
  s.userData.size = size;
  return s;
}

function ball(r, color, opacity = 1) {
  return new Mesh(new SphereGeometry(r, 24, 16),
    new MeshBasicMaterial({ color, transparent: true, opacity }));
}

function wireGlobe(r, color, opacity) {
  const pos = [];
  const push = (a, b) => { pos.push(a.x, a.y, a.z, b.x, b.y, b.z); };
  for (let k = -2; k <= 2; k++) {
    const lat = (k / 3) * Math.PI / 2, rr = r * Math.cos(lat), yy = r * Math.sin(lat);
    let prev = null;
    for (let i = 0; i <= 48; i++) {
      const a = (i / 48) * Math.PI * 2;
      const p = new Vector3(rr * Math.cos(a), yy, rr * Math.sin(a));
      if (prev) push(prev, p);
      prev = p;
    }
  }
  for (let j = 0; j < 6; j++) {
    const lon = (j / 6) * Math.PI;
    let prev = null;
    for (let i = 0; i <= 48; i++) {
      const a = (i / 48) * Math.PI * 2;
      const p = new Vector3(r * Math.cos(a) * Math.cos(lon), r * Math.sin(a), r * Math.cos(a) * Math.sin(lon));
      if (prev) push(prev, p);
      prev = p;
    }
  }
  const g = new BufferGeometry();
  g.setAttribute('position', new Float32BufferAttribute(pos, 3));
  return new LineSegments(g, new LineBasicMaterial({ color, transparent: true, opacity }));
}

function markBase(group) {
  group.traverse((c) => { if (c.material) { c.material.transparent = true; c.userData.base = c.material.opacity; } });
}
function setFade(group, o) {
  group.visible = o > 0.001;
  if (!group.visible) return;
  group.traverse((c) => { if (c.material && c.userData.base !== undefined) c.material.opacity = c.userData.base * o; });
}

/* ------------------------------------------------------------- star field */
{
  const n = 800, a = new Float32Array(n * 3);
  for (let i = 0; i < n; i++) {
    const r = 4000 + Math.random() * 3000;
    const th = Math.random() * Math.PI * 2, ph = Math.acos(2 * Math.random() - 1);
    a[i * 3] = r * Math.sin(ph) * Math.cos(th);
    a[i * 3 + 1] = r * Math.cos(ph);
    a[i * 3 + 2] = r * Math.sin(ph) * Math.sin(th);
  }
  const g = new BufferGeometry();
  g.setAttribute('position', new BufferAttribute(a, 3));
  const stars = new Points(g, new PointsMaterial({
    color: PALE, size: 1.8, sizeAttenuation: false, transparent: true, opacity: 0.5
  }));
  stars.frustumCulled = false;
  scene.add(stars);
}

/* ================================================================== act 1 */
const A1 = new Group();
world.add(A1);

const rE1 = M.earthRadiusKm / S1;
A1.add(ball(rE1, 0x0d2136, 1));
A1.add(wireGlobe(rE1, ACCENT, 0.55));

const raiseLines = DATA.raises.map((r, i) =>
  polyline(r.pts, S1, i === 0 ? SLATE : ACCENT, i === 0 ? 0.5 : 0.75));
raiseLines.forEach((l) => { l.geometry.setDrawRange(0, 0); A1.add(l); });

const escLine = polyline(DATA.escape, S1, ACCENT, 0.95);
escLine.geometry.setDrawRange(0, 0);
A1.add(escLine);

const soiRing = new Mesh(
  new RingGeometry(M.soiKm / S1 * 0.997, M.soiKm / S1, 160),
  new MeshBasicMaterial({ color: SLATE, transparent: true, opacity: 0, side: DoubleSide })
);
soiRing.rotation.x = Math.PI / 2;
A1.add(soiRing);

const craft1 = dot(PALE, 0.016);
const burn1 = dot(AMBER, 0.05, 0, true);
A1.add(craft1, burn1);
markBase(A1);

/* ================================================================== act 2 */
const A2 = new Group();
world.add(A2);

// Neither body is to scale here; at this zoom the real Sun would be a pixel.
A2.add(dot(AMBER, 0.055, 0.95));
A2.add(dot(AMBER, 0.16, 0.20, true));
{ // full circle, not just the arc Earth covers during the transfer: at this
  // zoom the transfer arc and Earth's path differ by about 1%, so the partial
  // arc was invisible underneath it. The ring is what gives the scene scale.
  const ring = [];
  for (let i = 0; i <= 256; i++) {
    const a = (i / 256) * Math.PI * 2;
    ring.push([Math.cos(a) * M.auKm, Math.sin(a) * M.auKm, 0]);
  }
  A2.add(polyline(ring, S2, SLATE, 0.3));
}

const arcLine = polyline(DATA.transfer, S2, ACCENT, 0.95);
arcLine.geometry.setDrawRange(0, 0);
A2.add(arcLine);

const earth2 = dot(0x6ba8e8, 0.022);
const craft2 = dot(PALE, 0.014);
A2.add(earth2, craft2);
markBase(A2);

/* ================================================================== act 3 */
const A3 = new Group();
world.add(A3);

// L1 sits at the origin of act 3; Earth goes along +x at the real offset.
const dxEarth = (M.earthRotKm - M.xL1Km) / S3;
const rE3 = 0.62;
const earth3 = ball(rE3, 0x0d2136, 1);
earth3.position.x = dxEarth;
const earth3wire = wireGlobe(rE3, ACCENT, 0.4);
earth3wire.position.x = dxEarth;
A3.add(earth3, earth3wire);

{
  const g = new BufferGeometry();
  g.setAttribute('position', new Float32BufferAttribute([-30, 0, 0, dxEarth, 0, 0], 3));
  A3.add(new LineSegments(g, new LineBasicMaterial({ color: SLATE, transparent: true, opacity: 0.28 })));
  const s = 0.8, c = new BufferGeometry();
  c.setAttribute('position', new Float32BufferAttribute(
    [-s, 0, 0, s, 0, 0, 0, -s, 0, 0, s, 0, 0, 0, -s, 0, 0, s], 3));
  A3.add(new LineSegments(c, new LineBasicMaterial({ color: AMBER, transparent: true, opacity: 0.7 })));
}

const haloRel = DATA.halo.map((p) => [p[0] - M.xL1Km, p[1], p[2]]);
A3.add(polyline(haloRel, S3, SLATE, 0.2));
const haloLine = polyline(haloRel, S3, ACCENT, 0.95);
haloLine.geometry.setDrawRange(0, 0);
A3.add(haloLine);

// Just the final stretch of the cruise, de-spun into the rotating frame, so the
// craft is seen arriving from somewhere rather than appearing on the halo.
const cosT = Math.cos(-M.thetaTransfer), sinT = Math.sin(-M.thetaTransfer);
const tailRel = DATA.transfer.slice(-11).map((p) => [
  p[0] * cosT - p[1] * sinT - M.xL1Km,
  p[0] * sinT + p[1] * cosT,
  p[2]
]);
A3.add(polyline(tailRel, S3, ACCENT, 0.35));

const craft3 = dot(PALE, 0.014);
const burn3 = dot(AMBER, 0.05, 0, true);
A3.add(craft3, burn3);
markBase(A3);

/* --------------------------------------------------------------- captions */
const CAPTIONS = [
  [0.0,   'Parking orbit',                     '235 × 19,500 km, inclined 19.2°'],
  [1.3,   'Burn 1 at perigee',                 'apogee → 22,459 km'],
  [3.35,  'Burn 2 at perigee',                 'apogee → 40,225 km'],
  [5.4,   'Burn 3 at perigee',                 'apogee → 71,767 km'],
  [7.45,  'Burn 4 at perigee',                 'apogee → 121,973 km'],
  [9.5,   'Coasting to perigee',               'the Oberth effect makes this the cheapest place to burn'],
  [11.55, 'Escape burn',                       `${M.escapeDvMs} m/s, and Earth no longer holds it'`],
  [13.4,  'Crossing the sphere of influence',  '925,000 km, 9.2 days after the burn'],
  [15.5,  'Heliocentric frame',                'Earth’s orbital motion is the spacecraft’s too'],
  [17.6,  'Lambert transfer arc',              '110 days from the sphere of influence to L1'],
  [23.5,  'Sun, Earth, spacecraft',            'the whole transfer in one frame'],
  [27.0,  'Locking to the rotating frame',     'Earth held fixed on the Sun–Earth line'],
  [29.0,  'Arrival at L1',                     '1,491,551 km sunward of Earth'],
  [30.6,  'Insertion burn',                    '265 m/s onto the halo'],
  [32.6,  'Halo orbit',                        'A_z = 120,000 km, one lap every 177.9 days'],
  [39.5,  'Unstable by nature',                'holding it costs 0.2–0.4 m/s of station-keeping']
];

const elPhase = document.getElementById('cap-phase');
const elNote = document.getElementById('cap-note');
const elClock = document.getElementById('clock');
let lastCap = -1;

function caption(t) {
  let i = 0;
  for (let k = 0; k < CAPTIONS.length; k++) if (t >= CAPTIONS[k][0]) i = k;
  if (i !== lastCap) {
    lastCap = i;
    elPhase.textContent = CAPTIONS[i][1];
    elNote.textContent = CAPTIONS[i][2];
  }
}

function missionDay(t) {
  if (t < A1_ESC0) return (t / A1_ESC0) * 4.6;
  if (t < ACTS[0].t1) return 4.6 + span(t, A1_ESC0, ACTS[0].t1) * M.escapeDays;
  if (t < ACTS[1].t1) return 4.6 + M.escapeDays + span(t, ACTS[1].t0, ACTS[1].t1) * M.transferDays;
  return 4.6 + M.escapeDays + M.transferDays + span(t, ACTS[2].t0 + 1.6, ACTS[2].t1) * M.haloDays * 2;
}

/* ----------------------------------------------------------------- camera */
// What each act needs to hold in frame, in its own world units.
/** Centre and radius that just contain a polyline, in that act's world units. */
function bounds(pts, scale) {
  let lo = [Infinity, Infinity, Infinity], hi = [-Infinity, -Infinity, -Infinity];
  for (const p of pts) for (let i = 0; i < 3; i++) {
    if (p[i] < lo[i]) lo[i] = p[i];
    if (p[i] > hi[i]) hi[i] = p[i];
  }
  const c = new Vector3((lo[0] + hi[0]) / 2 / scale, (lo[1] + hi[1]) / 2 / scale, (lo[2] + hi[2]) / 2 / scale);
  let r = 0;
  for (const p of pts) {
    const d = Math.hypot(p[0] / scale - c.x, p[1] / scale - c.y, p[2] / scale - c.z);
    if (d > r) r = d;
  }
  return { c: toWorld(c), r };
}

// Frame each raise on the ellipse itself rather than on Earth: an ellipse's
// far side is twice as far as its semi-major axis, so centring on Earth wastes
// half the frame.
const RB = DATA.raises.map((x) => bounds(x.pts, S1));
const EB = bounds(DATA.escape, S1);

const R1_KEYS = (() => {
  const k = [[0, RB[0].r * 1.2]];
  for (let i = 0; i < 5; i++) k.push([A1_INTRO + i * A1_ORBIT - 0.3, RB[i].r * 1.2]);
  k.push([A1_ESC0 - 0.2, RB[4].r * 1.2]);
  k.push([A1_ESC1, EB.r * 1.1]);
  return k;
})();
const T1_KEYS = (() => {
  const k = [[0, RB[0].c]];
  for (let i = 0; i < 5; i++) k.push([A1_INTRO + i * A1_ORBIT - 0.3, RB[i].c]);
  k.push([A1_ESC0 - 0.2, RB[4].c]);
  k.push([A1_ESC1, EB.c]);
  return k;
})();

/** Same as track(), for Vector3 keyframes. */
function trackVec(keys, t, out) {
  if (t <= keys[0][0]) return out.copy(keys[0][1]);
  for (let i = 1; i < keys.length; i++) {
    if (t <= keys[i][0]) {
      return out.copy(keys[i - 1][1]).lerp(keys[i][1], smooth(span(t, keys[i - 1][0], keys[i][0])));
    }
  }
  return out.copy(keys[keys.length - 1][1]);
}

const R2_KEYS = [
  [ACTS[1].t0,       10],
  [ACTS[1].t0 + 2.2, 34],
  [ACTS[1].t1 - 4.0, M.auKm / S2 * 1.18],
  [ACTS[1].t1,       M.auKm / S2 * 1.18]
];

const R3_KEYS = [
  [ACTS[2].t0,       6],
  [ACTS[2].t0 + 4.0, 9.6],
  [ACTS[2].t1,       9.6]
];
// The halo's loop lies roughly in the plane normal to the Sun-Earth line, so
// looking down that line shows it face-on. Straight down it would hide Earth
// behind the camera, so the view sits about 35 degrees off it.
const A3_TARGET_X = dxEarth * 0.46;

const camPos = new Vector3();
const camTgt = new Vector3();
const orbit = (az, el, d, out) =>
  out.set(Math.cos(az) * Math.cos(el) * d, Math.sin(el) * d, Math.sin(az) * Math.cos(el) * d);

function placeCamera(t) {
  if (t < ACTS[0].t1) {
    const g = span(t, 0, ACTS[0].t1);
    trackVec(T1_KEYS, t, camTgt);
    orbit(0.55 + g * 1.25, MathUtils.lerp(0.5, 0.28, smooth(g)), fitDistance(track(R1_KEYS, t)), camPos);
    camPos.add(camTgt);
    return;
  }
  if (t < ACTS[1].t1) {
    const g = span(t, ACTS[1].t0, ACTS[1].t1);
    // Start looking at the spacecraft near Earth, hand over to the Sun as the
    // frame widens, so the zoom-out reveals rather than jumps.
    craft2.getWorldPosition(camTgt);
    camTgt.multiplyScalar(1 - smooth(span(t, ACTS[1].t0 + 1.4, ACTS[1].t1 - 4.5)));
    orbit(-0.5 + g * 0.55, MathUtils.lerp(0.16, 0.72, smooth(g)), fitDistance(track(R2_KEYS, t)), camPos);
    camPos.add(camTgt);
    return;
  }
  const g = span(t, ACTS[2].t0, ACTS[2].t1);
  orbit(MathUtils.lerp(-0.30, -0.72, smooth(g)),
    MathUtils.lerp(0.10, 0.40, smooth(clamp01(g / 0.5))),
    fitDistance(track(R3_KEYS, t)), camPos);
  camTgt.set(A3_TARGET_X, 0, 0);
  camPos.add(camTgt);
}

/* ----------------------------------------------------------------- update */
const nR = DATA.raises.map((r) => r.pts.length);
const nEsc = DATA.escape.length;
const nArc = DATA.transfer.length;
const nHalo = DATA.halo.length;

function flash(sprite, amount, base) {
  sprite.material.opacity = amount * 0.95 * base;
  sprite.scale.setScalar(sprite.userData.size * (0.7 + (1 - amount) * 1.6));
}

function update(t) {
  caption(t);
  elClock.textContent = `T + ${missionDay(t).toFixed(1)} d`;

  /* ---- act 1 */
  const a1 = t < ACTS[0].t1 ? 1 : 1 - span(t, ACTS[0].t1, ACTS[0].t1 + 1.0);
  setFade(A1, a1);
  if (a1 > 0) {
    let burn = 0;
    for (let k = 0; k < 5; k++) {
      const s = A1_INTRO + k * A1_ORBIT;
      const f = span(t, s, s + A1_ORBIT);
      raiseLines[k].geometry.setDrawRange(0, Math.round(f * nR[k]));
      if (f > 0 && f < 1) {
        craft1.position.copy(at(DATA.raises[k].pts, S1, f * (nR[k] - 1)));
        if (k > 0 && f < 0.14) burn = 1 - f / 0.14;
      }
    }
    if (t < A1_INTRO) craft1.position.copy(at(DATA.raises[0].pts, S1, 0));

    const fe = span(t, A1_ESC0, A1_ESC1);
    escLine.geometry.setDrawRange(0, Math.round(fe * nEsc));
    if (fe > 0) {
      craft1.position.copy(at(DATA.escape, S1, fe * (nEsc - 1)));
      if (fe < 0.1) burn = Math.max(burn, 1 - fe / 0.1);
    }
    burn1.position.copy(craft1.position);
    flash(burn1, burn, a1);
    soiRing.material.opacity = 0.28 * span(t, A1_ESC0 + 1.0, A1_ESC1) * a1;
  }

  /* ---- act 2 */
  const a2 = Math.min(span(t, ACTS[0].t1 - 0.7, ACTS[0].t1 + 0.5),
                      1 - span(t, ACTS[1].t1 - 0.3, ACTS[1].t1 + 0.8));
  setFade(A2, a2);
  if (a2 > 0) {
    const f = span(t, ACTS[1].t0, ACTS[1].t1 - 2.6);
    arcLine.geometry.setDrawRange(0, Math.round(f * nArc));
    craft2.position.copy(at(DATA.transfer, S2, f * (nArc - 1)));
    const th = f * M.thetaTransfer;
    earth2.position.set(Math.cos(th) * M.auKm / S2, Math.sin(th) * M.auKm / S2, 0);
    // De-spin at the end of the act, so the frame hands over already locked to
    // the Sun-Earth line that act 3 works in.
    A2.rotation.z = -M.thetaTransfer * f * smooth(span(t, ACTS[1].t1 - 2.4, ACTS[1].t1));
  }

  /* ---- act 3 */
  const a3 = span(t, ACTS[1].t1 - 0.6, ACTS[1].t1 + 0.6);
  setFade(A3, a3);
  if (a3 > 0) {
    const arrive = span(t, ACTS[2].t0, ACTS[2].t0 + 1.6);
    const g = span(t, ACTS[2].t0 + 1.6, ACTS[2].t1);
    const laps = 2;
    haloLine.geometry.setDrawRange(0, g <= 0 ? 0 : Math.round(Math.min(1, g * laps) * nHalo));
    if (g <= 0) craft3.position.copy(at(tailRel, S3, arrive * (tailRel.length - 1)));
    else craft3.position.copy(at(haloRel, S3, (g * laps * (nHalo - 1)) % (nHalo - 1)));
    burn3.position.copy(craft3.position);
    flash(burn3, 1 - clamp01(Math.abs(t - (ACTS[2].t0 + 1.6)) / 0.5), a3);
  }

  placeCamera(t);
  camera.position.copy(camPos);
  camera.lookAt(camTgt);
}

/* -------------------------------------------------------------- transport */
let time = 0, playing = false, last = 0, allowed = true;

const btn = document.getElementById('play');
const bar = document.getElementById('bar');
const fill = document.getElementById('fill');
const chapEls = Array.from(document.querySelectorAll('.chap'));

function setPlaying(v) {
  playing = v && allowed && !reduce;
  btn.setAttribute('aria-label', playing ? 'Pause' : 'Play');
  btn.dataset.state = playing ? 'playing' : 'paused';
}

function paint() {
  fill.style.width = (time / DUR * 100).toFixed(2) + '%';
  bar.setAttribute('aria-valuenow', time.toFixed(1));
  let act = 0;
  for (let i = 0; i < ACTS.length; i++) if (time >= ACTS[i].t0) act = i;
  chapEls.forEach((c, i) => c.classList.toggle('on', i === act));
}

function seek(t) {
  time = MathUtils.clamp(t, 0, DUR);
  update(time);
  paint();
}

btn.addEventListener('click', () => {
  if (time >= DUR - 0.01) { seek(0); setPlaying(true); return; }
  setPlaying(!playing);
});
chapEls.forEach((c, i) => c.addEventListener('click', () => { seek(ACTS[i].t0 + 0.02); setPlaying(true); }));

function scrubFrom(e) {
  const r = bar.getBoundingClientRect();
  seek(clamp01((e.clientX - r.left) / r.width) * DUR);
}
let scrubbing = false;
bar.addEventListener('pointerdown', (e) => { scrubbing = true; bar.setPointerCapture(e.pointerId); scrubFrom(e); });
bar.addEventListener('pointermove', (e) => { if (scrubbing) scrubFrom(e); });
bar.addEventListener('pointerup', (e) => { scrubbing = false; try { bar.releasePointerCapture(e.pointerId); } catch (_) {} });
bar.addEventListener('keydown', (e) => {
  if (e.key === 'ArrowRight') { seek(time + 1); e.preventDefault(); }
  if (e.key === 'ArrowLeft') { seek(time - 1); e.preventDefault(); }
  if (e.key === ' ' || e.key === 'Enter') { setPlaying(!playing); e.preventDefault(); }
});

/* --------------------------------------------- visibility, in page and out */
// Inside an iframe an IntersectionObserver only sees the iframe's own viewport,
// so the parent tells us when the embed is actually on screen. Standalone, no
// message ever arrives and we simply play.
let heardFromParent = false;
window.addEventListener('message', (e) => {
  if (!e.data || e.data.type !== 'viewer-visibility') return;
  heardFromParent = true;
  allowed = !!e.data.visible;
  if (!allowed) setPlaying(false);
  else if (time < DUR - 0.01) setPlaying(true);
});

document.addEventListener('visibilitychange', () => {
  if (document.hidden) setPlaying(false);
  else if (allowed && time < DUR - 0.01) setPlaying(true);
});

/* -------------------------------------------------------------------- loop */
function frame(now) {
  requestAnimationFrame(frame);
  const dt = Math.min((now - last) / 1000, 0.05);
  last = now;
  if (playing) {
    time += dt;
    if (time >= DUR) { time = DUR; setPlaying(false); }
    update(time);
    paint();
  }
  renderer.render(scene, camera);
}

resize();
update(0);
paint();
setPlaying(false);
requestAnimationFrame((n) => { last = n; frame(n); });

if (reduce) {
  seek(ACTS[2].t0 + 8);
  document.getElementById('shell').classList.add('static');
} else {
  setTimeout(() => { if (!heardFromParent) { allowed = true; setPlaying(true); } }, 800);
}

window.__viewer = { seek, resize, get time() { return time; }, get playing() { return playing; }, DUR, ACTS };
